Pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),

]

pizzas/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from . import views


app_name = 'pizzas'

urlpatterns = [
    path('',views.index, name='index'),
    path('menu',views.menu, name='menu'),
    path('menu/<int:pizza_id>/',views.pizza, name='pizza'),
    path('new_comment/<int:pizza_id>/', views.new_comment, name='new_comment'),
    path('picture', views.pizza, name = 'picture'),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

pizzas/models.py
from tabnanny import verbose
from django.db import models

# Create your models here.



class Pizza(models.Model):
    pizza_name = models.CharField(max_length=200)
    picture = models.ImageField(upload_to='images/')


    def __str__(self):
        return self.pizza_name


class Toppings(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    topping_name = models.TextField(null=True)
    

    class Meta:
        verbose_name_plural = 'toppings'

    def __str__(self):
        return self.topping_name

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    comment = models.CharField(max_length=200)

    def __str__(self):
        return self.comment

pizzas/forms.py
from django import forms

from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']
        labels = {'comment':''}
        widgets = {'comment':forms.Textarea(attrs={'cols':80})}

pizzas/views.py
from django.shortcuts import render, redirect
from .forms import CommentForm
from .models import Pizza, Toppings

# Create your views here.

def index(request):
    return render(request, 'pizzas/index.html')

def menu(request):
    menu = Pizza.objects.all()

    context = {'menu':menu}

    return render(request, 'pizzas/menu.html', context)

def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.toppings_set.all()
    comment = pizza.comment_set.all()
    
    context = {'pizza':pizza, 'toppings':toppings, 'comment':comment} 

    return render(request, 'pizzas/pizza.html', context)


def new_comment(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)

    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.pizza = pizza
            new_comment.save()
            return redirect('pizzas:pizza', pizza_id=pizza_id)
    context = {'form':form, 'pizza':pizza} 
    return render(request, 'pizzas/new_comment.html', context)

pizzas/templates/pizzas/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>
            <a href="{% url 'pizzas:index' %}" >Pizzeria </a>
        </title>
        {% bootstrap_css %}
        {% bootstrap_javascript %}

    </head>


    <body>

        <!-- Static navbar -->

    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                </button>
                <a class="navbar-brand" href="{% url 'pizzas:index' %}">
                    Pizzeria</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'pizzas:menu' %}" >Menu </a></li>
                </ul>

            
            </div><!--/.nav-collapse -->

        </div>
    </nav>
        <div class="container">

            <div class="page-header">
                {% block header %}{% endblock header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>
        
        </div> <!-- /container -->
        
    </body>
</html>

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %} 
{% block header %} 
    <div class="jumbotron">
        <h1>Aidan's Pizzeria</h1>
    </div>
{% endblock header %} 

{% block content %}
    <h2>
        <a href="{% url 'pizzas:menu' %}">View Menu</a> for each pizza's toppings.
    </h2>

{% endblock content %} 

pizzas/templates/pizzas/menu.html
{% extends "pizzas/base.html" %} 

{% block header %} 
<h1>Pizzeria Menu</h1>
{% endblock header %} 

{% block content %} 


<ul>
    {% for p in menu %} 

    <li>
        <h3>
            <a href="{% url 'pizzas:pizza' p.id %}">{{ p }} </a>
        </h3>
    </li>
    {% empty %} 
    <li>There are no pizzas on the menu currently</li>
    {% endfor %}
</ul>

{% endblock content %} 

pizzas/templates/pizzas/new_comment.html
{% extends "pizzas/base.html" %} 


{% block content %} 
<p><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
</p>

<form action="{% url 'pizzas:new_comment' pizza.id %}" method="post">

    {% csrf_token %} 

    {{form.as_p}} 

    <button name="submit">Add Comment</button>
</form>

{% endblock content %} 

pizzas/templates/pizzas/old_templates.html
<p>
    <a href="{% url 'pizzas:index' %}" >Pizzeria </a>
    <a href="{% url 'pizzas:menu' %}" >Menu </a>
</p>

{% block content %} 


{% endblock content %} 

, initial-scale=1"

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %} 

{% block header %} 
<h1> {{ pizza }} Pizza </h1>
{% endblock header %}


{% block content %} 

<div>
<img src="{{ pizza.picture.url }}" width=400 height=auto/>
</div>

<h3>
    Toppings:
</h3>
<ul>
    {% for t in toppings %} 
    <li>
        <h3> <small>{{ t.topping_name }} 
            </small>
        </h3>
    </li>
    {% endfor %} 
</ul>

<h3>
    Comments: 
</h3>
<h3>
    <a href="{% url 'pizzas:new_comment' pizza.id %}">Add a comment</a>
</h3>
    {% for c in comment %} 
    <li><h3> <small>{{ c }} 
            </small>
        <h3>
    </li>
    {% endfor %} 

{% endblock content %} 